service: main

provider:
  name: aws
  stage: ${env:RELEASE_STAGE, 'aisight13'}
  region: ${env:AWS_REGION, 'eu-west-1'}

params:
  default:
    vpcSecondDigitCidrBlock: 10
    resourcenamespace: '${self:service}-${sls:stage}'
    resourceprefix: '${param:resourcenamespace}-'

resources:
  - ${file(resources/vpc.yml)}
  - Outputs:
      VpcOutput:
        Value: !Ref VPC
        Export:
          Name: ${sls:stage}-VPC
      SubnetAPublic:
        Value: !Ref SubnetAPublic
        Export:
          Name: ${sls:stage}-SubnetAPublic
      SubnetAPrivate:
        Value: !Ref SubnetAPrivate
        Export:
          Name: ${sls:stage}-SubnetAPrivate
      SubnetBPublic:
        Value: !Ref SubnetBPublic
        Export:
          Name: ${sls:stage}-SubnetBPublic
      SubnetBPrivate:
        Value: !Ref SubnetBPrivate
        Export:
          Name: ${sls:stage}-SubnetBPrivate
      SubnetCPublic:
        Value: !Ref SubnetCPublic
        Export:
          Name: ${sls:stage}-SubnetCPublic
      SubnetCPrivate:
        Value: !Ref SubnetCPrivate
        Export:
          Name: ${sls:stage}-SubnetCPrivate
